apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nginx
spec:
  minReplicas: 4
  maxReplicas: 10
  metrics:
    # - type: Pods
    #   pods:
    #     metricName: openconn
    #     targetAverageValue: 100
    - type: Resource
      resource:
        name: cpu #memory
        target:
          type: Utilization
          averageUtilization: 2 
          # 50% from all pods requests
  # scaleTargetRef:
  #   apiVersion: apps/v1
  #   kind: Deployment
  #   name: nginx
